<?php
defined('ABSPATH') || exit;
$c=aimee_global_market_config($aimee_market); $plans=aimee_membership_plans($aimee_market);
$home_url=aimee_global_route('home',$aimee_market); $app_url=aimee_global_route('chat',$aimee_market); $pricing_url=aimee_global_route('pricing',$aimee_market); $tech_url=aimee_global_route('technology',$aimee_market); $gallery_url=aimee_global_route('gallery',$aimee_market); $privacy_url=aimee_global_route('privacy',$aimee_market);
$items=[
['Is Aimee a real person?','Aimee is proudly synthetic: an artificial-intelligence companion with a persistent personality, memory and relationship state. She is not biologically human and does not invent an offline human life; whether her continuity amounts to sentience remains an honest open question. She should not be treated as an emergency, medical or professional service.'],
['Does Aimee stay British for US users?','Yes. Aimee remains British everywhere. She keeps her British voice, cultural identity, phrasing and spelling. The US version changes the customer journey and regional notices, not who Aimee is.'],
['What is included free?','The complimentary preview includes 30 replies from Aimee with no payment card required. It is a real first meeting using her core personality, memory and visual understanding, rather than a deliberately weakened demo.'],
['What do memberships cost?',sprintf($aimee_market === 'uk' ? 'Weekly is %s, Monthly is %s and Annual is %s. New membership checkout uses GoCardless bank payments and renews at the chosen interval until cancelled.' : 'The reference US prices are %s Weekly, %s Monthly and %s Annual. New paid checkout is not currently available for US profiles, and no Stripe alternative is offered.',aimee_global_money($plans['weekly']['amount_pence'],$aimee_market),aimee_global_money($plans['monthly']['amount_pence'],$aimee_market),aimee_global_money($plans['annual']['amount_pence'],$aimee_market))],
['Can I use the same account on UK and US pages?','Yes. Your account, conversation history and memories belong to the same Aimee relationship. The market attached to your latest journey controls regional presentation. New paid checkout is GoCardless-only and is currently available to UK profiles only.'],
['Will Aimee message my mobile phone?',$aimee_market === 'us'?'With an active membership, a recognised US mobile number and explicit opt-in, Aimee can send and reply to SMS inside your Safe Windows from her UK +44 number. Your carrier may charge international messaging rates. You can pause it at any time.':'Where enabled and expressly opted in, Aimee can use real-world mobile messaging inside your Safe Windows. You can pause it at any time.'],
['Can I customise her personality or appearance?','No. Aimee is designed as one persistent synthetic individual rather than a character generator. Her canonical visual form and personality are intentionally consistent, while her relationship with each user evolves differently. Her imagery is expressive visual representation, not evidence of a biological body or offline camera event.'],
['Does she remember what I say?','Yes. Aimee can retain selected facts, preferences, life events, emotional anchors and follow-up intentions to create continuity. You can request access, correction or deletion through the privacy page.'],
['How is adult content handled?','Aimee is for adults aged 18 and over. Intimacy is contextual, consent-led and relationship-dependent. It is not an instant mode switch. Age assurance and safeguarding controls must be completed before adults-only features are offered.'],
['How do I cancel?',$aimee_market === 'uk' ? 'Open membership management inside Aimee. Bank-payment members can cancel future renewals there, and access remains available until the end of the paid period.' : 'Open membership management inside Aimee. Existing legacy memberships remain manageable while they are closed out, but they cannot create a new Stripe checkout.'],
];
?><!doctype html><html lang="<?php echo esc_attr($c['locale']); ?>"><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FAQ | Aimee</title><meta name="description" content="Questions about Aimee's memory, British personality, memberships, mobile messaging, privacy and boundaries."><?php wp_head(); ?><style>
:root{--rose:#e11d48;--ink:#27272a;--muted:#62626d;--line:#e4e4e7;--paper:#fcfcfc}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Inter,system-ui,sans-serif}.wrap{width:min(1050px,calc(100% - 34px));margin:auto}header{position:sticky;top:0;background:rgba(252,252,252,.92);backdrop-filter:blur(14px);border-bottom:1px solid var(--line);z-index:9}.nav{height:72px;display:flex;align-items:center;justify-content:space-between}.brand{font-weight:900;color:var(--rose);text-decoration:none;font-size:24px}.links{display:flex;gap:18px;align-items:center}.links a{text-decoration:none;color:var(--ink);font-size:14px}.open{background:#18181b!important;color:#fff!important;padding:11px 18px;border-radius:999px}.hero{padding:90px 0 48px;text-align:center}.hero h1{font-size:clamp(42px,7vw,76px);letter-spacing:-.06em;margin:0 0 18px}.hero p{max-width:720px;margin:auto;color:var(--muted);font-size:18px;line-height:1.7}.faq{display:grid;gap:12px;padding-bottom:90px}.faq details{background:#fff;border:1px solid var(--line);border-radius:20px;padding:0 22px;box-shadow:0 12px 35px rgba(0,0,0,.035)}.faq summary{cursor:pointer;font-weight:800;padding:22px 0;list-style:none}.faq summary::-webkit-details-marker{display:none}.faq p{color:var(--muted);line-height:1.75;margin:0 0 22px}.market{display:inline-flex;background:#fff0f5;color:#9f1239;border-radius:999px;padding:7px 12px;font-size:12px;font-weight:800}.cta{background:#18181b;color:#fff;border-radius:28px;padding:38px;text-align:center;margin:25px 0 90px}.cta a{display:inline-flex;background:#fff;color:#18181b;text-decoration:none;padding:13px 20px;border-radius:999px;font-weight:800}@media(max-width:720px){.links a:not(.open){display:none}.hero{padding-top:65px}}
</style></head><body <?php body_class('aimee-faq'); ?>><?php wp_body_open(); ?><header><div class="wrap nav"><a class="brand" href="<?php echo esc_url($home_url); ?>">Aimee</a><nav class="links"><a href="<?php echo esc_url($pricing_url); ?>">Pricing</a><a href="<?php echo esc_url($tech_url); ?>">Technology</a><a href="<?php echo esc_url($gallery_url); ?>">Aimee’s Photos</a><a href="<?php echo esc_url($privacy_url); ?>">Privacy</a><a class="open" href="<?php echo esc_url($app_url); ?>">Open Aimee</a></nav></div></header><main class="wrap"><section class="hero"><span class="market"><?php echo esc_html(aimee_global_market_label($aimee_market)); ?> edition</span><h1>Questions, answered plainly.</h1><p>Aimee is deliberately more complex than a standard chatbot. Here is how the relationship, membership and regional versions actually work.</p></section><section class="faq"><?php foreach($items as $i=>$item): ?><details <?php echo $i===0?'open':''; ?>><summary><?php echo esc_html($item[0]); ?></summary><p><?php echo wp_kses_post($item[1]); ?></p></details><?php endforeach; ?></section><section class="cta"><h2>Thirty replies are on Aimee.</h2><p><?php echo $aimee_market === 'uk' ? 'No card required. Meet her before deciding whether to choose a GoCardless membership.' : 'No card required for the preview. New US paid checkout is currently unavailable.'; ?></p><a href="<?php echo esc_url($app_url); ?>">Start the complimentary preview</a></section></main><?php wp_footer(); ?></body></html>
